PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX airo: <https://w3id.org/airo#>
PREFIX vair: <https://w3id.org/vair#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 

SELECT  ?risk ?impact 
    ASK WHERE { ?system a airo:AISystem ;
                    airo:hasRisk ?risk .
            ?risk airo:hasConsequence ?consequence .
            ?consequence airo:hasImpact ?impact .
            ?impact airo:hasImpactOnArea ?area .
            ?area rdf:type vair:Health . }